---
- name: Gather current VPC configuration
  local_action:
    module: ec2_vpc
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    instance_tenancy: default
    internet_gateway: True
    region: "{{ region }}"
  register: vpc
