---
- name: Gather current VPC configuration
  local_action:
    module: ec2_vpc
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    instance_tenancy: default
    internet_gateway: True
    region: "{{ region }}"
  register: vpc
